app/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('main.urls', namespace='main')),
    
  
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.contrib import admin
from django.urls import path
from main import views
from django.conf import settings
from django.conf.urls.static import static

app_name='main'

urlpatterns = [
    
    path('', views.index, name='index'),
    path('about/', views.about, name="about"),
    path('contact/', views.contact, name="contact"),
    
    
]

main/models.py
from os import name
from tabnanny import verbose
from django.core.validators import slug_re
from django.db import models

class Catalog(models.Model):
   name= models.CharField(max_length=150, unique=True, verbose_name='Название')
   slug =models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
   
   class Meta:
       db_table='catalog'
       verbose_name='Каталог'
       verbose_name_plural='Каталоги'
       
  
    
       
       

  
        
       

main/views.py
from main.models import Catalog
from django.http import HttpResponse
from django.shortcuts import render
from django.template import context


def index(request):
    
    catalog=Catalog.objects.all()
    
    
    context = {
        'content':'Пластиковые окна для Вашего дома',
        'catalog': catalog
    }
    
    return render(request,'main/index.html', context)


def about(request):
    
    
    
    
    context = {
        'content':'О нас',
        'text_on_the_page':'Наша компания – лидер в производстве и установке пластиковых окон на российском рынке. Наша миссия – создавать комфорт и уют в каждом доме, предлагая высококачественные, экологически чистые и энергоэффективные оконные конструкции. Мы используем передовые технологии и материалы, чтобы удовлетворить потребности самых требовательных клиентов. Мы ваш надежный партнер в создании комфортного и безопасного жилища. Мы предлагаем только лучшие решения для вашего дома, обеспечивая высокое качество, энергоэффективность и долговечность наших оконных конструкций. Обратитесь к нам, и мы сделаем ваш дом уютным и теплым!'
       
    }
    return render(request,'main/about.html', context)


def contact(request):
    context = {
        'content':'Контактная информация',
        'text_on_page':'Адрес: Латвия, г. Рига, ул. Бривибас, д. 100, офис 20',
       
    }
    return render(request,'main/contact.html', context)

main/templates/main/about.html
{% extends "main/base.html" %}
    {% load static %}

    {% block content %}
    <container class="bg-white">
        <h2 class="mt-5 text-dark"><strong>{{ content }}</strong></h2>
        <p class="m-1 text-dark">{{ text_on_the_page }}</p>
    </container>
   
    
   
        {% endblock content %} 

      
   

main/templates/main/base.html
<!DOCTYPE html>
<html lang="ru">
  <head>
   
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Home</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap/my.css' %}" />
    <link
      rel="stylesheet"
      href="{% static 'bootstrap/css/bootstrap.min.css' %}"



       
    />
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
  </head>


  <body>

    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand " href="{% url "main:index" %}">JK and Co</a>

          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link text-white" href="{% url "main:index" %}">Начало</a>
              </li>

             
              <li class="nav-item">
                <a class="nav-link text-white" href="{% url "main:about" %}">О нас</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-white" href="{% url "main:contact" %}">Контактная информация</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-white" href="">Обратная связь</a>
              </li>

             

              <li>
                <hr class="dropdown-divider" >
              </li>
            </ul>

            <form class="d-flex" role="search">
              <input
                class="form-control me-2"
                type="search"
                placeholder="Search"
                aria-label="Search"
              />
              <button class="btn btn-outline-success text-white" type="submit">
                Поиск
              </button>
            </form>


           

                <a class='text-white' href="https://www.facebook.com/">      <div class="ms-5">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
                    <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951"/>
                  </svg>
                </div> </a>

                <a class='text-white' href=""><div class="ms-5">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
                    <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.9 3.9 0 0 0-1.417.923A3.9 3.9 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.9 3.9 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.9 3.9 0 0 0-.923-1.417A3.9 3.9 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599s.453.546.598.92c.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.5 2.5 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.5 2.5 0 0 1-.92-.598 2.5 2.5 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233s.008-2.388.046-3.231c.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92s.546-.453.92-.598c.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92m-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217m0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334"/>
                  </svg>
    
                </div></a>
           

            
            
          </div>
        </div>
      </nav>
    </header>

    <section>
     
      <div class="container">
      {% block catalog %}
      {% endblock catalog %}

       
      </div> 
    </section>

{% block content %}


{% endblock content %}




    

    <footer>

    



          <div class="foot">
          
              
              <div class="text-light">
              
                  <p> Copyright JK & Co Web Studio 2024 </p>
              
              </div>
              <div>
                <p><a class="text-light" href="">Политика конфиденциальности</a></p>
              </div>
            </div> 



     
    </footer>




    <script src="{% static "bootstrap\js\jquery-3.7.0.min.js"%}"></script>
    <script src="{% static "bootstrap\js\jquery-events.js"%}"></script>
    <script src="{% static "bootstrap\js\jquery-ajax.js"%}"></script>
    <script src="{% static "bootstrap\js\bootstrap.bundle.min.js"%}"></script>
  
  </body>
</html>

main/templates/main/contact.html
{% extends "main/base.html" %}
    {% load static %}
  
    {% block content %}
    <div  class="about-1">
        <h2 class="mt-5 text-dark"><strong>{{ content }}</strong></h2>
        <p class="m-2 text-dark">{{ text_on_page }}</p>
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2175.3026992408886!2d24.127853696272485!3d56.96074723012985!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x46eecfcac3ce638b%3A0x72f4cc0eeaf73399!2zQnLEq3bEq2JhcyBpZWxhIDEwMCwgQ2VudHJhIHJham9ucywgUsSrZ2EsIExWLTEwMDE!5e0!3m2!1sru!2slv!4v1721743568650!5m2!1sru!2slv" width="800" height="600" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>
{% endblock content %}

main/templates/main/index.html
{% extends "main/base.html" %}
    {% load static %}

{% block content %}


<h1 class="mt-5 pt-5 text-dark text-center"><strong>{{ content }}</strong></h1></div> 


<main>
  <div
    id="carouselExampleControls"
    class="carousel slide"
    data-bs-ride="carousel"
  >
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img
          src="..\media\DRUTEX_SHOWROOM_10.jpg"
          class="d-block w-100"
          alt="..."
        />
      </div>
      <div class="carousel-item">
        <img
          src="..\media\DRUTEX_SHOWROOM_18.jpg"
          class="d-block w-100"
          alt="..."
        />
      </div>
      <div class="carousel-item">
        <img
          src="..\media\DRUTEX_SHOWROOM_19.jpg"
          class="d-block w-100"
          alt="..."
        />
      </div>
    </div>
    <button
      class="carousel-control-prev"
      type="button"
      data-bs-target="#carouselExampleControls"
      data-bs-slide="prev"
    >
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Предыдущий</span>
    </button>
    <button
      class="carousel-control-next"
      type="button"
      data-bs-target="#carouselExampleControls"
      data-bs-slide="next"
    >
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Следующий</span>
    </button>
  </div>

</main>
{% endblock content %}



{% block catalog %}

<div class="row mt-1 position-fixed z-3"> 
    <!-- Каталог -->
     <div class="dropdown mb-2">
        <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
            aria-expanded="false">
            Каталог
            <img class="mx-1" src="{% static "/icons/grid-fill.svg"%}" alt="Catalog Icon" width="16"
                height="16">
        </button>

        <ul class="dropdown-menu bg-dark" data-bs-theme="dark">
          {% for katal  in catalog  %}
                <li><a class="dropdown-item text-white" href="{% url "main:index"%}">{{ katal.name }}</a></li>
                {% endfor %}
           
    
        </ul>
      </div> 
    </div>
    
{% endblock catalog %}




    

   